// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

abstract class MouseEventType {
  static const int LeftButtonDown = 0;
  static const int LeftButtonUp = 1;
  static const int MiddleButtonDown = 2;
  static const int MiddleButtonUp = 3;
  static const int RightButtonDown = 4;
  static const int RightButtonUp = 5;
  static const int MouseMove = 6;
  static const int MouseWheel = 7;
  static const int MouseHorizontalWheel = 8;
}

final class MouseEvent extends ffi.Struct {
  @ffi.Int32()
  external int eventType;

  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

  @ffi.Int64()
  external int wheelDelta;
}
